export const ORDER_TYPE_CONSTANTS = {
  ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',
  ORDER_CREATE_RESET: 'ORDER_CREATE_RESET',

  ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
  ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
  ORDER_DETAILS_FAILED: 'ORDER_DETAILS_FAILED',
  ORDER_DETAILS_RESET: 'ORDER_DETAILS_RESET',

  ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
  ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
  ORDER_PAY_FAILED: 'ORDER_PAY_FAILED',

  ORDER_PAY_RESET: 'ORDER_PAY_RESET',

  ORDER_LIST_MY_REQUEST: 'ORDER_LIST_MY_REQUEST',
  ORDER_LIST_MY_SUCCESS: 'ORDER_LIST_MY_SUCCESS',
  ORDER_LIST_MY_FAILED: 'ORDER_LIST_MY_FAILED',
  ORDER_LIST_MY_RESET: 'ORDER_LIST_MY_RESET',

  //! ADMIN

  ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
  ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
  ORDER_LIST_FAILED: 'ORDER_LIST_FAILED',
  ORDER_LIST_RESET: 'ORDER_LIST_RESET',

  ORDER_DELIVER_REQUEST: 'ORDER_DELIVER_REQUEST',
  ORDER_DELIVER_SUCCESS: 'ORDER_DELIVER_SUCCESS',
  ORDER_DELIVER_FAILED: 'ORDER_DELIVER_FAILED',
  ORDER_DELIVER_RESET: 'ORDER_DELIVER_RESET',
}
